import Nav from '@/app/component/navBar'
import './globals.css'
import { Inter } from 'next/font/google'
import CartProvider from '@/context/context'
import Footer from './component/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'دالي ترافل',
  description: 'Generated by Mahmoud Saad',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <CartProvider>
     <body className={inter.className}>
        <Nav/>
        {children}
        </body>
        <Footer />
     </CartProvider>
    </html>
  )
}
